export const GET_PRODUCTLIST_SUCCESS = 'GET_PRODUCTLIST_SUCCESS';
export const GET_PRODUCTLIST_FAILURE = 'GET_PRODUCTLIST_FAILURE';
export const GET_PRODUCTLIST_PENDING = 'GET_PRODUCTLIST_PENDING';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';


export const GET_CART_DETAILS_SUCCESS = 'GET_CART_DETAILS_SUCCESS';
export const GET_CART_DETAILS_FAILURE = 'GET_CART_DETAILS_FAILURE';
export const GET_CART_DETAILS_PENDING = 'GET_CART_DETAILS_PENDING';

export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const CLEAR_CART_QUANTITY = 'CLEAR_CART_QUANTITY';

export const UPDATE_SHOP_QUERY = 'UPDATE_SHOP_QUERY'